kind: Service
apiVersion: v1
metadata:
  labels:
    app: infinispan-server
  name: infinispan-server-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: infinispan-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinispan-server
spec:
  replicas: 2
  selector:
    matchLabels:
      name: infinispan-server
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        name: infinispan-server
        app: infinispan-server
    spec:
      serviceAccountName: jgroups-kubeping-service-account
      containers:
      - args:
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        name: infinispan-server
        image: kocacnargiray/infinispan-cache:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 7800
          protocol: TCP          
        - containerPort: 8181
          protocol: TCP
        - containerPort: 8888
          protocol: TCP
        - containerPort: 9990
          protocol: TCP
        - containerPort: 11211
          protocol: TCP
        - containerPort: 11222
          protocol: TCP
        resources:
          requests:
            cpu: "500m"
      imagePullSecrets:
      - name: infinispansecret

